name: pontaj_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Localization
  intl: any

  envied: ^1.3.2

  # State management & routing
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1

  # Freezed & JSON serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0

  # UI & utilities
  google_fonts: ^8.0.0
  fl_chart: ^1.1.1
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # PDF generation
  pdf: ^3.11.3
  printing: ^5.14.2

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1

  # Google Sign-In
  google_sign_in: ^7.2.0

  # Local preferences
  shared_preferences: ^2.5.4

  # URL launching
  url_launcher: ^6.3.2
  firebase_app_check: ^0.4.1+4

  # Web platform detection
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  envied_generator:
  freezed: ^3.2.4
  json_serializable: ^6.12.0

flutter:
  generate: true
  uses-material-design: true